# Generated by Django 6.1 on 2026-08-27 21:29

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnqueueLock",
            fields=[
                ("key", models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "блокировка допуска",
                "verbose_name_plural": "блокировки допуска",
            },
        ),
        migrations.CreateModel(
            name="CommandState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="команда")),
                ("enabled", models.BooleanField(default=True, verbose_name="включена")),
                (
                    "disabled_reason",
                    models.TextField(blank=True, verbose_name="причина выключения"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="изменено")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кем изменено",
                    ),
                ),
            ],
            options={
                "verbose_name": "состояние команды",
                "verbose_name_plural": "состояния команд",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "command",
                    models.CharField(db_index=True, max_length=255, verbose_name="команда"),
                ),
                ("arguments", models.JSONField(blank=True, default=dict, verbose_name="аргументы")),
                ("argv", models.JSONField(blank=True, default=list, verbose_name="argv")),
                (
                    "lock_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, verbose_name="ключ блокировки"
                    ),
                ),
                ("timeout", models.PositiveIntegerField(default=0, verbose_name="таймаут, с")),
                (
                    "requested_by_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="кто запустил (снимок)"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="причина запуска")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("running", "Выполняется"),
                            ("succeeded", "Успешно"),
                            ("failed", "Ошибка"),
                            ("canceled", "Отменён до старта"),
                            ("stopped", "Остановлен оператором"),
                            ("timed_out", "Превышен таймаут"),
                            ("unknown", "Потерян — результат неизвестен"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="создан"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="начат")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="завершён"),
                ),
                (
                    "heartbeat_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="последний heartbeat"),
                ),
                ("hostname", models.CharField(blank=True, max_length=255, verbose_name="хост")),
                ("pid", models.PositiveIntegerField(blank=True, null=True, verbose_name="PID")),
                (
                    "runner_ref",
                    models.CharField(blank=True, max_length=255, verbose_name="ссылка раннера"),
                ),
                (
                    "exit_code",
                    models.IntegerField(blank=True, null=True, verbose_name="код возврата"),
                ),
                ("error", models.TextField(blank=True, verbose_name="ошибка супервизора")),
                (
                    "stop_requested_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="остановка запрошена"),
                ),
                (
                    "stop_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soft", "Мягкая (SIGTERM, через паузу SIGKILL)"),
                            ("hard", "Жёсткая (SIGKILL сразу)"),
                        ],
                        max_length=8,
                        verbose_name="режим остановки",
                    ),
                ),
                ("output_tail", models.TextField(blank=True, verbose_name="хвост вывода")),
                ("output_bytes", models.BigIntegerField(default=0, verbose_name="объём вывода")),
                (
                    "log_path",
                    models.CharField(blank=True, max_length=500, verbose_name="архив лога"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exec_tool_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто запустил",
                    ),
                ),
                (
                    "stop_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кем запрошена остановка",
                    ),
                ),
            ],
            options={
                "verbose_name": "запуск",
                "verbose_name_plural": "запуски",
                "ordering": ("-created_at",),
                "permissions": [("run_command", "Может запускать команды из белого списка")],
            },
        ),
        migrations.CreateModel(
            name="RunOutputChunk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.PositiveIntegerField(verbose_name="порядковый номер")),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="создан"),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="django_exec_tool.run",
                    ),
                ),
            ],
            options={
                "verbose_name": "чанк вывода",
                "verbose_name_plural": "чанки вывода",
                "ordering": ("run", "seq"),
            },
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["command", "status"], name="django_exec_command_4821e0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="runoutputchunk",
            unique_together={("run", "seq")},
        ),
    ]
